### PR TITLE
Added hook to confirm marketplace subscription

### PR DESCRIPTION
**Pull request by Sylistron**
Does so right after a successful registration

### CODE REVIEW

**Comment by rpgreen** [comment]
For all of these PRs I have the same questions:
+ What is the expected behavior for customers not using AWS Marketplace? i.e. direct subscription through the dev portal
+ These routes are designed to take the registration token from the Marketplace site redirect, correct?
+ How did you test these changes?

**Comment by Sylistron** [comment]
Great questions and I'm making a TON of assumptions since I don't know how the original website worked that this entire thing is based on.

> What is the expected behavior for customers not using AWS Marketplace? i.e. direct subscription through the dev portal.

My assumption was that this portal was entirely for Marketplace users only and I'm surprised that this portal allowed sign-ups for non-Marketplace users.  

My thought to address is is to actually mark the UsagePlans in the lambdas/backend/catalog/index.js as Marketplace-only and non-Marketplace.  This will allow a developer, like me, to allow users access to a UsagePlan that gives them free access for trying out an API or use some other payment method.

I will change the /apis page to match Marketplace users to Marketplace UsagePlans and non-Marketplace to users to non-Marketplace UsagePlans.  

> These routes are designed to take the registration token from the Marketplace site redirect, correct?

Yes

> How did you test these changes?

I actually setup a Marketplace Listing and clicked the subscribe button there.  My listing isn't live on the Marketplace, it's in "preview" mode.  I can't give you access to the listing for testing, so you'll have to setup your own.

**Comment by rpgreen** [comment]
This sounds good in general.

"I will change the /apis page to match Marketplace users to Marketplace UsagePlans and non-Marketplace to users to non-Marketplace UsagePlans."

Can you clarify this? Here's how I think this should work:
-All users should see all usage plans on the catalog. 
-Usage plans marked as "marketplace only" should be visible to all users in the catalog, but can only be subscribed to via the marketplace subscription process.
-Usage plans marked as "non-marketplace" can be subscribed to by any user in the developer portal

**Comment by Sylistron** [comment]
I like that better than mine - I'll even add in a "marketplaceUrl" so that the user can see a link to the Listing, sign-up for an AWS account (or sign-in) and purchase there.

**Pull request closed without merging**
