### PR TITLE
Allow usage of existing user pool

### PR DESCRIPTION
**Pull request by nimrodkor**
*Description of changes:*
Added two parameters to allow usage of existing User Pool instead of creating a new one.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by amazon-meaisiah** [comment]
Could you fix the merge conflicts?

**Comment by nimrodkor** [comment]
@amazon-meaisiah Done!

**Comment by nimrodkor** [comment]
Hey again @amazon-meaisiah !

I tested it out on our environment - and for some reason, the URL for the existing cognito user pool is broken in the UI. When I try to sign in, it sends me to `https://developers.test.com/<COGNITO_URL>`
Tried to fix it but had a hard time. Any possible help here?

**Comment by amazon-meaisiah** [comment]
@nimrodkor Not sure personally based on a cursory look at the code, but I'll see if I can work with other team members to figure out what's going on or if I just missed something.

**Comment by nimrodkor** [comment]
@amazon-meaisiah Removed the temp files, sorry about that!

**Comment by talipini** [comment]
@nimrodkor - Looks like this change was merged in a while ago but it is not in the latest any more. Any ideas on what happened to it? Were there any issues with this? thanks

**Pull request closed without merging**
